### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by yael-vinker** [kingnobro/IconShop#1]
Hi, nice work!
I downloaded your data following the instructions.
However, it seems like the preprocessed data is not structured as a path sequence.
For example if I open ""
this is the text file:
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">\n  <path d="M131 12v6h53v164l5 1 5 1v8l-94 1H7v-10h4l5-1V18h52l1-6V7h62v5M34 56v24h26V56l-12-1c-10 0-13 0-14 1m53 12v12h26V55H87v13m52-12v13l1 11h26V56l-13-1c-10 0-13 0-14 1m-79 59c-1 1-1 16-1 33l1 32h80v-66h-40c-32 0-40 0-40 1"/>\n</svg>
![image](https://github.com/kingnobro/IconShop/assets/42582557/23ebed59-0a94-4b86-bbe7-cd9ae6519d12)

As can be seen, the SVG is constructed weirdly, without paths.
Did you use this data for training? or did you apply some additional preprocess to FIGR8?
Thanks

**Comment by kingnobro** [comment]
Hello. SVG data in FIGR8 can contain various numbers of paths. The SVG you referenced contains only one path, but includes several 'Move' commands to draw the windows and the door. Why are there numerous 'Move' commands in the same path? They are used to create 'fill' properties. More information can be found here: https://oreillymedia.github.io/Using_SVG/extras/ch06-fill-rule.html

To answer your question, since this SVG has only one path, we use this data for training. However, many SVGs contain multiple paths.
